version: '3.1'
services:
    backend:
        image: 'bedasoftware/aidbox-sdc:latest'
        env_file:
            - env_tests
        depends_on:
            devbox-healthcheck:
                condition: service_healthy
        links:
            - devbox
        healthcheck:
            test: curl --fail http://backend:8081/live || exit 1
            interval: 1s
            timeout: 20s
            retries: 100
    devbox-healthcheck:
        image: curlimages/curl
        entrypoint: /bin/sleep 10000
        links:
            - devbox
        depends_on:
            - devbox
        healthcheck:
            test: curl --fail http://devbox:8080/__healthcheck || exit 1
            interval: 1s
            timeout: 20s
            retries: 100
    devbox:
        image: healthsamurai/aidboxone:edge
        depends_on:
            - devbox-db
        links:
            - 'devbox-db:database'
        env_file:
            - env_tests
        environment:
            AIDBOX_LICENSE: ${AIDBOX_LICENSE}
        ports:
            - 8181:8080
    devbox-db:
        image: healthsamurai/aidboxdb:14.5
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: devbox
    ready:
        image: hello-world
        depends_on:
            backend:
                condition: service_healthy
