version: '3.1'
services:
  sdc:
    image: bedasoftware/fhir-sdc:latest
    depends_on:
      devbox-healthcheck:
        condition:
          service_healthy
    links:
      - devbox
    env_file:
      - devenv/sdc
    volumes:
      - ./config:/var/config:cached
    # Colored logs
    tty: true
  devbox-healthcheck:
    image: curlimages/curl
    entrypoint: /bin/sleep 10000
    links:
      - devbox
    depends_on:
      - devbox
    healthcheck:
      test: curl --fail http://devbox:8080/__healthcheck || exit 1
      interval: 1s
      timeout: 20s
      retries: 100
  devbox:
    image: healthsamurai/aidboxone:stable
    depends_on:
      - devbox-db
    links:
      - devbox-db:database
    env_file:
      - devenv/aidbox
      - .env
    volumes:
      - ./config:/var/config:cached
      - ./devzenproject:/zenproject
    ports:
      - 8080:8080
  devbox-db:
    image: healthsamurai/aidboxdb:16.1
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:       devbox
  jute:
      image: bedasoftware/jute-microservice:latest
      ports:
          - '8099:8090'
  fhirpath_mapping:
      image: bedasoftware/fhirpath-extract:main
      ports:
          - '8091:8090'
